apiVersion: v1
kind: Service
metadata:
  labels:
    app: scenarioiq-api 
    env: scenarioiq-api
  name: scenarioiq-api-service
  namespace: dev-ui
spec:
  clusterIP: 
  externalIPs:
  -  10.248.41.32
  externalTrafficPolicy: Cluster
  ports:
  - name: port
    nodePort: 32200
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: scenarioiq-api 
    env: scenarioiq-api
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}