apiVersion: v1
kind: Service
metadata:
  labels:
    app: scenarioiq-ui 
    env: scenarioiq-ui
  name: scenarioiq-ui-service
  namespace: dev-ui
spec:
  clusterIP: 
  externalIPs:
  -  10.248.41.32
  externalTrafficPolicy: Cluster
  ports:
  - name: port
    nodePort: 31402
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: scenarioiq-ui 
    env: scenarioiq-ui
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}